# Generated by Django 3.2.5 on 2021-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='post_images'),
            preserve_default=False,
        ),
    ]
